language: node_js
node_js:
- 6.2.0
before_install:
- npm run install-dependencies
notifications:
  hipchat:
    rooms:
      secure: R4ebAIcb0KfCf6WNNd/rU9dEG1pmEkiHZEwbMvn1TyMK9gUHaQguWqJBx8w8KiQ37VdPeK1462Tic3Dvgifm7/U4cTrYZ3eYSUy6Qvufar9RMZXHPmJNpOg+ift5mtf32UebT7k94JGmuKe1BoWcGupQbNMzbzOcxrqfHVAhHsp8AZ+xGBjjM2Ig88HETPdzIfB4cJoL5VpUCACBPtmKSJpsVhTl/7lfvlN2iSUuW13XXjGTEMrbOSYPL44Wt2rn7DkxeIV2aJGOeWSmHovbxf9DQdsfNXhKy9SRuj+lyvGVLUNUnDTfP6y5wKoQpS7CWyJDpYcWLVAMvUcPW6fqa82XJ4P7Ukys0QbWzQWo/GHzZnm+LmYk8ChUJBMrIMo3H2KoJTUIFWybPXFKvx0uIKOX/dMIiAX7mDqXap0HKEWnGkzb4lwbWmkn7YiF74xRvKP/nkJwlr/mOaKUJbc0ymnGpqlYorohmBDNGhwRo/KkF6k+9vWypJOGOZLxjSMoav6tH4oqt/OAdGUSZKQtBeyYCutSgwWVAhxfhia58amer4uGlpiqdoLMawTplpsKUS9B342g0ugUXJ38KWalNa0aLSkQW/6xkdi2Xmbt7yUmha0N5CQMPwdZCCcYNq/rQr6FcU+LcNaodsVEpsORhglWRkya1YL/D5/Bakvz0MY=
